import { epochs } from '@mrpelz/modifiable-date';
import { FunctionComponent } from 'preact';
import { useMemo } from 'preact/hooks';

import { Hidden } from '../../components/hidden.js';
import {
  nextDayIncrement,
  useTimeIncrement,
} from '../../hooks/use-time-label.js';
import { globalProperties } from '../../state/global-properties.js';
import { $flags } from '../../util/flags.js';
import { HallwayStream } from '../../views/hallway-stream.js';
import { Room } from './room.js';

const cheesyDevQuotes = [
  'Today’s reminder: Kubernetes still doesn’t care about your feelings.',
  'If your code compiles, that’s already a small miracle.',
  '404 inspiration not found. Try again tomorrow.',
  'Every CI pipeline secretly judges you.',
  'Your uptime is higher than your confidence, for now.',
  'Sometimes the only cache you need to clear is your brain.',
  'Even microservices need emotional scaling.',
  'Don’t worry, that alert is just your ego catching fire.',
  'Rollback is cheaper than therapy.',
  'Commit messages are modern poetry, mostly tragic.',
  'Sometimes deploying is just a fancy way to procrastinate.',
  'Your logs are crying louder than you are.',
  'Remember: DNS doesn’t owe you clarity.',
  'Load balancers never give compliments.',
  'Refactoring is just rearranging chaos.',
  'Your branch is like your optimism: untested and doomed.',
  '404 motivation not found. Retry after coffee.',
  'Even the scheduler has better priorities than you.',
  'Sometimes you are the only pod running in your namespace.',
  'Prod doesn’t care about your excuses.',
  'Yesterday’s feature is today’s regret.',
  'Secrets belong in Vault, not in your head.',
  'The browser doesn’t forgive, it just freezes.',
  'Technical debt is cheaper than emotional debt.',
  'Your uptime is impressive only in hindsight.',
  'Scaling horizontally does not fix your attitude.',
  'Some incidents are personal, all are unavoidable.',
  'Your keyboard is a therapist you can ignore.',
  'Rollback feels like giving up, but it’s not.',
  'Your IDE knows more than your manager.',
  'Errors are the universe’s way of saying hi.',
  'Your microservices gossip more than your coworkers.',
  'Even Prometheus sometimes lies.',
  'Some commits are only noble in theory.',
  'Your cache is invalidated more often than your confidence.',
  'Latency hurts both metrics and souls.',
  'The CI never sleeps, but you should.',
  'Memory leaks are romantic compared to emotional ones.',
  'Even Kubernetes struggles with self-worth.',
  'Every merge is a leap of faith over a pit of exceptions.',
  'Your firewall is stricter than your discipline.',
  'Some alerts are philosophical exercises.',
  'Downtime is just the system reflecting your mood.',
  'You are not optional, but your pods are ephemeral.',
  'Sometimes the best feature is not shipping anything.',
  'Every failed deploy is a tiny character-building exercise.',
  'Your stack traces are more readable than your diary.',
  'Containers are more resilient than you on Monday.',
  'Today’s retry may fail, but so did your lunch.',
  'Your logs are holding grudges.',
  'Scaling vertically won’t fix your life choices.',
  'Even CI pipelines have trust issues.',
  'Some bugs are just passive-aggressive comments.',
  'Remember: devs who complain are still the only ones who commit.',
  'Your dependencies gossip more than you think.',
  'Sometimes the server is just silently judging you.',
  'Your dashboard is prettier than your social life.',
  'Even feature flags hide existential dread.',
  'The network drops packets and dreams alike.',
  'Your load balancer has better balance than your schedule.',
  'Sometimes the fastest solution is just a timeout.',
  'Your health checks are more attentive than your friends.',
  'Refactoring is therapy you can bill.',
  'Today’s deployment is tomorrow’s regret.',
  'Your branch may not merge, but at least it tried.',
  'Even Nginx has commitment issues.',
  'Some outages are spiritual experiences.',
  'Your stack is more complex than your emotions.',
  'Latency is the universe’s way of testing patience.',
  '404 inspiration found. But only in logs.',
  'Your code reviews are as cruel as reality.',
  'Scaling horizontally won’t scale your morale.',
  'Sometimes uptime is the only thing that matters.',
  'Your secrets are safer than your self-esteem.',
  'Every retry is a small existential victory.',
  'Your microservices whisper about your failures.',
  'The CI pipeline remembers everything.',
  'Even YAML can be cruel.',
  'Today’s alert is tomorrow’s anecdote.',
  'Your container never complains, and neither should you.',
  'Some endpoints are unreachable, like your motivation.',
  'Your tests mock more than your coworkers.',
  'Rollback early, rollback often.',
  'Your network latency is faster than your self-reflection.',
  'Even Grafana exaggerates the truth.',
  'Some commits are quietly heroic.',
  'Your pod is lonely, but it’s consistent.',
  'Memory leaks are emotionally resonant.',
  'Every merge conflict is a personal attack.',
  'Your error logs are more honest than your diary.',
  'Even Prometheus judges your habits.',
  'Today’s build may fail, but your spirit is optional.',
  'Some endpoints are deprecated, like your optimism.',
  'Your browser crashes, but you survive.',
  'Scaling horizontally won’t fix existential bugs.',
  'Even DNS is passive-aggressive.',
  'Your stack traces are like cryptic horoscopes.',
  'Some deployments are therapy sessions.',
  'Your CI pipeline is a relentless parent.',
  'Retrying is cheaper than emotional labor.',
  'Your IDE silently judges your lifestyle.',
  'Latency is a cruel teacher.',
  'Every incident is a character test you didn’t ask for.',
  'Your code smells are honest.',
  'Even Helm charts have secrets.',
  'Today’s logs contain hidden poetry.',
  'Rollback is self-care.',
  'Your microservices are snarky.',
  'Some alerts are philosophical riddles.',
  'Your dashboard is nicer than your apartment.',
  'Even CI pipelines grieve silently.',
  'Memory leaks are like unpaid rent.',
  'Your tests lie occasionally, like friends.',
  'Scaling vertically does not heal trauma.',
  'Your pods are ephemeral, like your attention span.',
  'Even Prometheus lies when it wants.',
  'Some commits are heroic in retrospect.',
  'Your stack is a complex metaphor for life.',
  'Today’s deploy may fail, but at least it’s honest.',
  'Latency will humble you if nothing else does.',
  'Your container is more resilient than your optimism.',
  'Rollback is courage with a timeout.',
  'Your logs are the closest thing to truth.',
  'Even YAML judges your creativity.',
  'Some endpoints are unreachable, like your motivation.',
  'Your CI pipeline never forgets.',
  'Memory leaks mimic heartbreaks.',
  'Scaling horizontally won’t help your confidence.',
  'Your IDE is a harsh critic.',
  'Even Nginx has commitment issues.',
  'Some errors are just existential commentary.',
  'Your stack traces are literary.',
  'Rollback is therapy in code.',
  'Your pods are lonely heroes.',
  'Latency is a silent mentor.',
  'Your tests gossip about you.',
  'Even Grafana exaggerates outcomes.',
  'Some commits are quietly noble.',
  'Your container never whines, unlike you.',
  'Retrying is cheaper than admitting mistakes.',
  'Your error logs are brutal mentors.',
  'Even Helm charts mock your choices.',
  'Today’s alert is tomorrow’s anecdote.',
  'Your network is a metaphor for life.',
  'Scaling vertically won’t fix morale.',
  'Your CI pipeline is emotionally unavailable.',
  'Some bugs are passive-aggressive critiques.',
  'Your stack is complex, like your life choices.',
  'Latency is a harsh truth-teller.',
  'Memory leaks are tiny tragedies.',
  'Even DNS has mood swings.',
  'Your pods are ephemeral, but your pride is eternal.',
  'Rollback often, regret rarely.',
  'Your logs are candid, unlike humans.',
  'Some endpoints refuse to cooperate, like coworkers.',
  'Your dashboard is prettier than your soul feels.',
  'Even Prometheus is judgmental today.',
  'Today’s deploy may fail, but at least you tried.',
  'Your tests mock reality subtly.',
  'Latency is a teacher with no empathy.',
  'Your CI pipeline is relentless, like time.',
  'Some commits are silent victories.',
  'Your container is stoic, unlike you.',
  'Memory leaks are emotional spoilers.',
  'Scaling horizontally won’t fix self-doubt.',
  'Even YAML can be cruel.',
  'Your pods gossip silently.',
  'Rollback is courage in action.',
  'Your logs are brutally honest.',
  'Some alerts are existential lessons.',
  'Your IDE is a cruel mentor.',
  'Latency is life’s reminder that you’re human.',
  'Your microservices whisper truths you avoid.',
  'Even Nginx feels passive-aggressive today.',
  'Some deployments are character tests.',
  'Your stack traces are cryptic prophecies.',
  'Rollback is self-care disguised as action.',
  'Your pods are lonely, but persistent.',
  'Memory leaks are like emotional baggage.',
  'Your CI pipeline is unforgiving.',
  'Some commits are heroic in hindsight.',
  'Your tests occasionally lie.',
  'Even Grafana exaggerates your achievements.',
  'Latency teaches humility.',
  'Scaling vertically won’t improve your mood.',
  'Your container is the model citizen.',
  'Rollback early, rollback often, cry quietly.',
  'Your logs are brutally honest diaries.',
  'Some endpoints are metaphorically unreachable.',
  'Your dashboard lies about happiness.',
  'Even Prometheus has opinions.',
  'Today’s deploy may fail, but your dignity is optional.',
  'Your IDE silently judges all life choices.',
  'Memory leaks are small tragedies.',
  'Scaling horizontally doesn’t fix broken dreams.',
  'Your pods are ephemeral, like fleeting motivation.',
  'Rollback is courage with grace.',
  'Your tests are occasionally cruel.',
  'Some commits are unappreciated heroics.',
  'Latency will humble your hubris.',
  'Your CI pipeline remembers everything.',
  'Even YAML has existential angst.',
  'Your stack traces are literary devices.',
  'Some errors are philosophical exercises.',
  'Your container endures silently.',
  'Rollback is self-care, repeated.',
  'Memory leaks mirror heartbreaks.',
  'Scaling vertically won’t heal your soul.',
  'Your logs are confessional.',
  'Even Nginx struggles with commitment.',
  'Some alerts are riddles from the universe.',
  'Your pods are stoic, unlike you.',
  'Latency is the most honest teacher.',
  'Your CI pipeline is emotionally distant.',
  'Rollback often, panic rarely.',
  'Your tests lie occasionally, humans lie always.',
  'Even Helm charts hold grudges.',
  'Memory leaks are life’s subtle reminders.',
  'Scaling horizontally doesn’t fix emotional debt.',
  'Your container keeps going, silently heroic.',
  'Some commits are noble in retrospect.',
  'Latency is a lesson in humility.',
  'Your dashboards exaggerate victories.',
  'Rollback is bravery with a timeout.',
  'Your logs are merciless narrators.',
  'Even Prometheus is judgmental today.',
  'Memory leaks are quietly tragic.',
  'Scaling vertically doesn’t mend confidence.',
  'Your pods whisper truths you ignore.',
  'Some endpoints are unreachable, like your motivation.',
  'Rollback is therapy in code.',
  'Your CI pipeline never forgets mistakes.',
  'Latency will humble you eventually.',
  'Your container is stoic, unlike you.',
  'Some deployments are silent character tests.',
  'Memory leaks mimic heartbreak.',
  'Even Grafana exaggerates honesty.',
  'Scaling horizontally won’t fix emotional bugs.',
  'Your logs are honest, like brutal mentors.',
  'Rollback early, panic never.',
  'Your pods endure quietly.',
  'Some commits are heroic underappreciated art.',
  'Latency is a patient teacher.',
  'Your CI pipeline judges silently.',
  'Memory leaks are emotional microservices.',
  'Even YAML mocks your creativity.',
  'Your container perseveres where you falter.',
  'Rollback is courage disguised as process.',
  'Your tests are merciless.',
  'Some alerts are existential exercises.',
  'Latency teaches what no manager will.',
  'Your pods are lonely, but persistent.',
  'Scaling vertically won’t scale confidence.',
  'Your logs are confessional essays.',
  'Even Prometheus exaggerates severity.',
  'Rollback often, question everything else.',
  'Memory leaks are tiny tragedies.',
  'Your container is resilient, unlike your ego.',
  'Some endpoints are unreachable, like dreams.',
  'Latency is a cruel mentor.',
  'Your CI pipeline never sleeps.',
  'Rollback is bravery, repeated.',
  'Your pods gossip silently.',
  'Even Grafana lies occasionally.',
  'Memory leaks mirror emotional baggage.',
  'Scaling horizontally won’t fix motivation.',
  'Your logs are brutally honest diaries.',
  'Some commits are quietly heroic.',
  'Latency humbles all.',
  'Rollback early, panic never.',
  'Your container endures silently.',
  'Memory leaks are tragedies disguised as metrics.',
  'Even Nginx judges your choices.',
  'Your pods are ephemeral philosophers.',
  'Rollback is self-care with a timeout.',
  'Your CI pipeline remembers all.',
  'Latency teaches patience.',
  'Scaling vertically won’t fix feelings.',
  'Your logs are more truthful than people.',
  'Some alerts are philosophical riddles.',
  'Memory leaks are emotional spoilers.',
  'Rollback often, regret rarely.',
  'Your container is stoic.',
  'Latency is life’s reminder of mortality.',
  'Your pods are the unsung heroes.',
  'Scaling horizontally won’t fix self-doubt.',
  'Your tests lie occasionally.',
  'Even YAML is cruel sometimes.',
  'Your logs are merciless.',
  'Rollback is therapy, repeated.',
  'Memory leaks mirror heartbreaks.',
  'Your CI pipeline is relentless.',
  'Latency is the most honest teacher.',
  'Your dashboards exaggerate victories.',
  'Rollback early, cry quietly.',
  'Your container perseveres silently.',
  'Some commits are noble in retrospect.',
  'Memory leaks are tiny tragedies.',
  'Scaling vertically won’t heal confidence.',
  'Your pods whisper truths.',
  'Even Prometheus judges.',
  'Rollback is courage disguised as action.',
  'Your tests are harsh critics.',
  'Latency humbles hubris.',
  'Your logs are brutal mentors.',
  'Scaling horizontally doesn’t fix everything.',
  'Your container is heroic silently.',
  'Memory leaks are subtle tragedies.',
  'Rollback often, regret never.',
  'Some endpoints are unreachable, like motivation.',
  'Latency is a patient mentor.',
  'Your CI pipeline remembers everything.',
  'Your pods endure quietly.',
  'Memory leaks are tiny heartbreaks.',
  'Rollback is self-care with a timeout.',
  'Your dashboards lie about happiness.',
  'Scaling vertically won’t fix confidence.',
  'Your logs are mercilessly honest.',
  'Some commits are underappreciated heroics.',
  'Latency teaches humility.',
  'Rollback early, panic never.',
  'Your container perseveres silently.',
  'Memory leaks mirror heartbreak.',
  'Your pods are lonely, but persistent.',
  'Even Grafana exaggerates truth.',
  'Scaling horizontally doesn’t fix self-doubt.',
  'Your CI pipeline judges silently.',
  'Rollback is courage repeated.',
  'Your tests lie occasionally.',
  'Memory leaks are life’s subtle reminders.',
  'Your logs are brutally honest.',
  'Latency will humble you eventually.',
  'Your container endures stoically.',
  'Scaling vertically won’t heal pride.',
  'Rollback often, regret rarely.',
  'Your pods whisper truths.',
  'Even Prometheus exaggerates.',
  'Memory leaks are emotional microservices.',
  'Rollback is therapy disguised as process.',
  'Your CI pipeline never forgets.',
  'Latency humbles all.',
  'Your logs are brutal mentors.',
  'Scaling horizontally won’t fix everything.',
  'Your container is quietly heroic.',
  'Memory leaks are tragedies in disguise.',
  'Rollback early, panic never.',
  'Your pods endure silently.',
  'Some commits are noble in retrospect.',
  'Latency teaches humility.',
  'Your dashboards exaggerate victories.',
  'Rollback often, regret never.',
  'Your container perseveres silently.',
  'Memory leaks mirror heartbreaks.',
  'Scaling vertically won’t mend confidence.',
  'Your logs are brutally honest.',
  'Rollback is courage with a timeout.',
  'Latency will humble you.',
  'Your CI pipeline remembers everything.',
  'Your pods are stoic heroes.',
  'Memory leaks are subtle tragedies.',
  'Scaling horizontally won’t fix self-doubt.',
  'Your tests lie occasionally.',
  'Rollback is therapy repeated.',
  'Your container endures silently.',
  'Latency humbles hubris.',
  'Your logs are merciless mentors.',
  'Some alerts are philosophical exercises.',
  'Memory leaks mimic heartbreaks.',
  'Rollback early, regret never.',
  'Your pods are unsung heroes.',
  'Scaling vertically won’t heal pride.',
  'Your CI pipeline judges silently.',
  'Latency teaches patience.',
  'Your container perseveres quietly.',
  'Memory leaks are tiny tragedies.',
  'Rollback often, panic never.',
  'Your dashboards lie about happiness.',
  'Your logs are brutally honest.',
  'Scaling horizontally doesn’t fix everything.',
  'Your container is quietly heroic.',
  'Latency humbles all.',
  'Rollback is courage disguised as process.',
  'Memory leaks mirror heartbreaks.',
  'Your CI pipeline never sleeps.',
  'Your pods endure silently.',
  'Some commits are quietly heroic.',
];

export const Global: FunctionComponent<{
  $properties: ReturnType<typeof globalProperties>;
}> = ({ $properties }) => {
  const now = useTimeIncrement(nextDayIncrement);

  const dayInYear = useMemo(() => {
    if (!now) return undefined;

    const start = new Date(now.getFullYear(), 0, 0);
    const diff =
      now.getTime() -
      start.getTime() +
      (start.getTimezoneOffset() - now.getTimezoneOffset()) * 60 * 1000;

    return Math.floor(diff / epochs.day);
  }, [now]);

  const cheesyDevQuote = useMemo(
    () =>
      dayInYear === undefined ? null : (cheesyDevQuotes.at(dayInYear) ?? null),
    [dayInYear],
  );

  return (
    <Room $properties={$properties}>
      <Hidden>{cheesyDevQuote}</Hidden>
      {$flags.hallwayStreamEnable.value ? <HallwayStream /> : null}
    </Room>
  );
};
