apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: iot-webinterface
  labels:
    app: iot-webinterface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-webinterface
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: iot-webinterface
    spec:
      containers:
        - image: {IMAGE}
          imagePullPolicy: IfNotPresent
          name: iot-webinterface
          ports:
            - containerPort: 1337
              name: http
              protocol: TCP
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
